# Generated by Django 5.0.6 on 2025-11-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="destacado",
            field=models.BooleanField(default=False),
        ),
    ]
