# Generated by Django 5.0.6 on 2025-11-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Amor y Aniversario", "Amor y Aniversario"),
                    ("Cumpleaños", "Cumpleaños"),
                    ("Agradecimiento", "Agradecimiento"),
                    ("Condolencias", "Condolencias"),
                ],
                max_length=100,
            ),
        ),
    ]
