# Generated by Django 5.0.6 on 2025-11-01 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Email', 'Email')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('enviado', 'enviado'), ('error', 'error')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
    ]
