# Generated by Django 5.0.6 on 2025-11-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_sitio",
                    models.CharField(default="Florería FloreSer", max_length=100),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="configuracion/"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="configuracion/"
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                ("horario_atencion", models.CharField(blank=True, max_length=100)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("whatsapp_numero", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Configuración del Sitio",
                "verbose_name_plural": "Configuración del Sitio",
                "db_table": "home_config",
            },
        ),
        migrations.CreateModel(
            name="SeccionInicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("subtitulo", models.CharField(blank=True, max_length=200)),
                ("contenido", models.TextField(blank=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="inicio/"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("banner", "Banner Principal"),
                            ("destacado", "Producto Destacado"),
                            ("testimonio", "Testimonio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("enlace", models.URLField(blank=True)),
                ("texto_boton", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Sección de Inicio",
                "verbose_name_plural": "Secciones de Inicio",
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="Testimonio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cargo", models.CharField(blank=True, max_length=100)),
                ("contenido", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="testimonios/"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Testimonio",
                "verbose_name_plural": "Testimonios",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
