# Generated by Django 5.0.6 on 2025-11-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="alto_imagen_ocasion",
            field=models.PositiveIntegerField(
                default=230,
                help_text='Altura en píxeles para las tarjetas de "Comprar por Ocación".',
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="alto_imagen_producto",
            field=models.PositiveIntegerField(
                default=220,
                help_text="Altura en píxeles para imágenes de productos y destacados.",
            ),
        ),
    ]
