# Generated by Django 5.0.6 on 2025-11-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_config_alto_imagen_ocasion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="alto_imagen_destacado",
            field=models.PositiveIntegerField(
                default=220,
                help_text="Altura en píxeles para productos destacados en la página de inicio.",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="alto_imagen_producto",
            field=models.PositiveIntegerField(
                default=220,
                help_text="Altura en píxeles para imágenes del catálogo de productos.",
            ),
        ),
    ]
