# Generated by Django 5.0.6 on 2025-11-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
